### ISSUE TITLE
does it work in 1.7.10 (FTB Infinity Evolved)

### ISSUE THREAD

**Issue by Muruxror** [merlinlikethewizard/Mastermine#32]
Hey,

I simply can't get it to work
the last two days I tried everything... 
newer mods, older mods, moving files from a to b... noting... 
I tried downloading both ways (simplified and old method) 
((btw: as many others... if I type "pastebin get CtcSGkpc mastermine.lua" I get an empty file))
I can edit the downloaded files but don't run them, when I try to run it, it just goes a line down and does nothing. 

I'm using FTB Infinity Evolved with all mods CC is v1.75 and Peripherals++ v1.3.6 in MC 1.7.10
am I doing something wrong, or is there no support for these versions?

**Comment by merlinlikethewizard** [comment]
Hi Muruxror,

I'm sorry you're having issues getting it to run properly. After some googling it looks like people have been having similar issues with the `pastebin` command for years. Since that seems to be a problem with the command itself I think the only option there is to download the files manually and move them into the floppy disk's directory in your save file.

However, it sounds like you've already tried that and not had any luck. Just so I can understand what's happening, can you describe at what stage in this process things stop working?

1. Copy files into the floppy disk's directory out-of-game
2. In-game, type `ls disk` and make sure the files are there
3. Run `disk/hub.lua` to copy over all files and start the program

After this the Hub should be working, otherwise there should be an error message, and if there's not even that then check to see if the files even copied over by typing `ls`. If you let me know where things go wrong I'd love to help you try to troubleshoot :)

**Comment by merlinlikethewizard** [comment]
Also, yes, this program (in theory) should work in those versions I believe.

**Comment by Muruxror** [comment]
Hey,
first, I'm very thankful for your support and your fast reply and help.
Nice that you are still maintaining your (awesome) project :).

I will describe what I did till now:
first I tried to download the files the easy way, with no success as stated as above. To locate the ID of the floppy (in the GUI was no way to tell this in my game) then I downloaded the file from Pastebin manually and replaced the empty file with the manually downloaded one, then I tried to edit it, to ensure there is code in the file, it was...
After that I tried to run `mastermine disk`, had to change it to `mastermine.lua disk` then the files were on the disk.
Then I tried to run `disk/hub.lua` with no result, no error no change on the monitor, noting happened.
I attached the pics of the files and the screen after I pressed enter.
I also tried to do it via the old way and copied all files from GitHub to another disk. It worked till the same point... I can edit the files, so they are there, but the same problem as the other way, when I try to run `disk/hub.lua` noting happens.
I hope you can help me with the provided info, maybe other with the same problems can relate to this ^^

![2021-12-14_13 13 10](https://user-images.githubusercontent.com/60011986/145996846-c298b317-efba-4adf-8d65-a6fc472068ad.png)
all files
![2021-12-14_13 13 54](https://user-images.githubusercontent.com/60011986/145996855-321406a1-7ba3-4bd8-b3a2-eab0cc2076a2.png)
after pressing enter 
![2021-12-14_13 14 07](https://user-images.githubusercontent.com/60011986/145996874-d3fd4e3d-e02a-4180-9363-4e53c09e98d2.png)
the monitor after pressing enter

**Comment by Muruxror** [comment]
Just found the fix for the download...
[https://youtu.be/MkloBnl-W8s](url)
just remembered it from the old days xD
I guess that is a problem in the older versions of CC, maybe that alone helps a lot of people...
But the program still won't start.

**Comment by Stevenw52** [comment]
Anyone figure this out?
